# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end
  # LDAP server
  config.vm.define "app1" do |app|
    app.vm.hostname = "server"
    app.vm.box = "geerlingguy/centos7"
    app.vm.network :private_network, ip: "192.168.80.2"
    app.vm.provision "file", source: "scripts/ldifs", destination: "$HOME/ldifs"
    app.vm.provision "shell", path: "scripts/server.sh", privileged: false
  end
  # LDAP client
  config.vm.define "app2" do |app|
    app.vm.hostname = "client"
    app.vm.box = "geerlingguy/centos7"
    app.vm.network :private_network, ip: "192.168.80.3"
    app.vm.provision "shell", path: "scripts/client.sh", privileged: false
  end
end
